import "./globals.css";
import { MainLayout } from "@/components/Layout/MainLayout";

export const metadata = {
  title: "Blackcoffer Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainLayout children={children} />
      </body>
    </html>
  );
}
