import "./globals.css";
import { Inter } from "next/font/google";
import { MainLayout } from "@/components/Layout/MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blackcoffer Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainLayout children={children} />
      </body>
    </html>
  );
}
